package com.tw.ddcs.model;

import java.util.Date;

public class Alert {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_telecommand.id
	 * @mbggenerated  Thu Aug 02 14:11:57 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_telecommand.inverter_sn
	 * @mbggenerated  Thu Aug 02 14:11:57 CST 2018
	 */
	private String inverter_sn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_telecommand.errorcode
	 * @mbggenerated  Thu Aug 02 14:11:57 CST 2018
	 */
	private String desc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_telecommand.message
	 * @mbggenerated  Thu Aug 02 14:11:57 CST 2018
	 */
	private String value;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_telecommand.datetime
	 * @mbggenerated  Thu Aug 02 14:11:57 CST 2018
	 */
	private Date datetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_telecommand.id
	 * @return  the value of ds_telecommand.id
	 * @mbggenerated  Thu Aug 02 14:11:57 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_telecommand.id
	 * @param id  the value for ds_telecommand.id
	 * @mbggenerated  Thu Aug 02 14:11:57 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_telecommand.inverter_sn
	 * @return  the value of ds_telecommand.inverter_sn
	 * @mbggenerated  Thu Aug 02 14:11:57 CST 2018
	 */
	public String getInverter_sn() {
		return inverter_sn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_telecommand.inverter_sn
	 * @param inverter_sn  the value for ds_telecommand.inverter_sn
	 * @mbggenerated  Thu Aug 02 14:11:57 CST 2018
	 */
	public void setInverter_sn(String inverter_sn) {
		this.inverter_sn = inverter_sn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_telecommand.errorcode
	 * @return  the value of ds_telecommand.errorcode
	 * @mbggenerated  Thu Aug 02 14:11:57 CST 2018
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_telecommand.errorcode
	 * @param desc  the value for ds_telecommand.errorcode
	 * @mbggenerated  Thu Aug 02 14:11:57 CST 2018
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_telecommand.message
	 * @return  the value of ds_telecommand.message
	 * @mbggenerated  Thu Aug 02 14:11:57 CST 2018
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_telecommand.message
	 * @param value  the value for ds_telecommand.message
	 * @mbggenerated  Thu Aug 02 14:11:57 CST 2018
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_telecommand.datetime
	 * @return  the value of ds_telecommand.datetime
	 * @mbggenerated  Thu Aug 02 14:11:57 CST 2018
	 */
	public Date getDatetime() {
		return datetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_telecommand.datetime
	 * @param datetime  the value for ds_telecommand.datetime
	 * @mbggenerated  Thu Aug 02 14:11:57 CST 2018
	 */
	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

}
