package com.tw.ddcs.model;

import java.util.Date;

public class SolarMan {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_solarman.id
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_solarman.inverter_sn
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	private String inverter_sn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_solarman.ipv1
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	private Float ipv1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_solarman.ipv2
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	private Float ipv2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_solarman.ipv3
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	private Float ipv3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_solarman.vpv1
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	private Float vpv1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_solarman.vpv2
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	private Float vpv2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_solarman.vpv3
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	private Float vpv3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_solarman.iac1
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	private Float iac1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_solarman.iac2
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	private Float iac2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_solarman.iac3
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	private Float iac3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_solarman.vac1
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	private Float vac1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_solarman.vac2
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	private Float vac2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_solarman.vac3
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	private Float vac3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_solarman.power
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	private Float power;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_solarman.frequency
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	private Float frequency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_solarman.temperature
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	private Float temperature;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_solarman.current_electric
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	private Float current_electric;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_solarman.total_electric
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	private Float total_electric;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_solarman.error_code
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	private Byte error_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_solarman.datetime
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	private Date datetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_solarman.provider_type
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	private Byte provider_type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_solarman.provider_station_id
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	private String provider_station_id;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_solarman.id
	 * @return  the value of ds_solarman.id
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_solarman.id
	 * @param id  the value for ds_solarman.id
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_solarman.inverter_sn
	 * @return  the value of ds_solarman.inverter_sn
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public String getInverter_sn() {
		return inverter_sn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_solarman.inverter_sn
	 * @param inverter_sn  the value for ds_solarman.inverter_sn
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public void setInverter_sn(String inverter_sn) {
		this.inverter_sn = inverter_sn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_solarman.ipv1
	 * @return  the value of ds_solarman.ipv1
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public Float getIpv1() {
		return ipv1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_solarman.ipv1
	 * @param ipv1  the value for ds_solarman.ipv1
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public void setIpv1(Float ipv1) {
		this.ipv1 = ipv1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_solarman.ipv2
	 * @return  the value of ds_solarman.ipv2
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public Float getIpv2() {
		return ipv2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_solarman.ipv2
	 * @param ipv2  the value for ds_solarman.ipv2
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public void setIpv2(Float ipv2) {
		this.ipv2 = ipv2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_solarman.ipv3
	 * @return  the value of ds_solarman.ipv3
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public Float getIpv3() {
		return ipv3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_solarman.ipv3
	 * @param ipv3  the value for ds_solarman.ipv3
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public void setIpv3(Float ipv3) {
		this.ipv3 = ipv3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_solarman.vpv1
	 * @return  the value of ds_solarman.vpv1
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public Float getVpv1() {
		return vpv1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_solarman.vpv1
	 * @param vpv1  the value for ds_solarman.vpv1
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public void setVpv1(Float vpv1) {
		this.vpv1 = vpv1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_solarman.vpv2
	 * @return  the value of ds_solarman.vpv2
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public Float getVpv2() {
		return vpv2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_solarman.vpv2
	 * @param vpv2  the value for ds_solarman.vpv2
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public void setVpv2(Float vpv2) {
		this.vpv2 = vpv2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_solarman.vpv3
	 * @return  the value of ds_solarman.vpv3
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public Float getVpv3() {
		return vpv3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_solarman.vpv3
	 * @param vpv3  the value for ds_solarman.vpv3
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public void setVpv3(Float vpv3) {
		this.vpv3 = vpv3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_solarman.iac1
	 * @return  the value of ds_solarman.iac1
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public Float getIac1() {
		return iac1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_solarman.iac1
	 * @param iac1  the value for ds_solarman.iac1
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public void setIac1(Float iac1) {
		this.iac1 = iac1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_solarman.iac2
	 * @return  the value of ds_solarman.iac2
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public Float getIac2() {
		return iac2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_solarman.iac2
	 * @param iac2  the value for ds_solarman.iac2
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public void setIac2(Float iac2) {
		this.iac2 = iac2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_solarman.iac3
	 * @return  the value of ds_solarman.iac3
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public Float getIac3() {
		return iac3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_solarman.iac3
	 * @param iac3  the value for ds_solarman.iac3
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public void setIac3(Float iac3) {
		this.iac3 = iac3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_solarman.vac1
	 * @return  the value of ds_solarman.vac1
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public Float getVac1() {
		return vac1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_solarman.vac1
	 * @param vac1  the value for ds_solarman.vac1
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public void setVac1(Float vac1) {
		this.vac1 = vac1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_solarman.vac2
	 * @return  the value of ds_solarman.vac2
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public Float getVac2() {
		return vac2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_solarman.vac2
	 * @param vac2  the value for ds_solarman.vac2
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public void setVac2(Float vac2) {
		this.vac2 = vac2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_solarman.vac3
	 * @return  the value of ds_solarman.vac3
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public Float getVac3() {
		return vac3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_solarman.vac3
	 * @param vac3  the value for ds_solarman.vac3
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public void setVac3(Float vac3) {
		this.vac3 = vac3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_solarman.power
	 * @return  the value of ds_solarman.power
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public Float getPower() {
		return power;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_solarman.power
	 * @param power  the value for ds_solarman.power
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public void setPower(Float power) {
		this.power = power;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_solarman.frequency
	 * @return  the value of ds_solarman.frequency
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public Float getFrequency() {
		return frequency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_solarman.frequency
	 * @param frequency  the value for ds_solarman.frequency
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public void setFrequency(Float frequency) {
		this.frequency = frequency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_solarman.temperature
	 * @return  the value of ds_solarman.temperature
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public Float getTemperature() {
		return temperature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_solarman.temperature
	 * @param temperature  the value for ds_solarman.temperature
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public void setTemperature(Float temperature) {
		this.temperature = temperature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_solarman.current_electric
	 * @return  the value of ds_solarman.current_electric
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public Float getCurrent_electric() {
		return current_electric;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_solarman.current_electric
	 * @param current_electric  the value for ds_solarman.current_electric
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public void setCurrent_electric(Float current_electric) {
		this.current_electric = current_electric;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_solarman.total_electric
	 * @return  the value of ds_solarman.total_electric
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public Float getTotal_electric() {
		return total_electric;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_solarman.total_electric
	 * @param total_electric  the value for ds_solarman.total_electric
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public void setTotal_electric(Float total_electric) {
		this.total_electric = total_electric;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_solarman.error_code
	 * @return  the value of ds_solarman.error_code
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public Byte getError_code() {
		return error_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_solarman.error_code
	 * @param error_code  the value for ds_solarman.error_code
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public void setError_code(Byte error_code) {
		this.error_code = error_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_solarman.datetime
	 * @return  the value of ds_solarman.datetime
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public Date getDatetime() {
		return datetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_solarman.datetime
	 * @param datetime  the value for ds_solarman.datetime
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_solarman.provider_type
	 * @return  the value of ds_solarman.provider_type
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public Byte getProvider_type() {
		return provider_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_solarman.provider_type
	 * @param provider_type  the value for ds_solarman.provider_type
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public void setProvider_type(Byte provider_type) {
		this.provider_type = provider_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_solarman.provider_station_id
	 * @return  the value of ds_solarman.provider_station_id
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public String getProvider_station_id() {
		return provider_station_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_solarman.provider_station_id
	 * @param provider_station_id  the value for ds_solarman.provider_station_id
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	public void setProvider_station_id(String provider_station_id) {
		this.provider_station_id = provider_station_id;
	}
}