package com.tw.ddcs.mybatis.mapper;

import java.util.List;

import com.tw.ddcs.model.Alert;

public interface AlertMapper extends BaseMapper<Alert>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_telecommand
	 * @mbggenerated  Thu Aug 02 14:11:57 CST 2018
	 */
	int insert(Alert record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_telecommand
	 * @mbggenerated  Thu Aug 02 14:11:57 CST 2018
	 */
	int insertSelective(Alert record);
	
	int batchInsert(List<Alert> list);

}
