package com.tw.ddcs.mybatis.mapper;

import java.util.List;

import com.tw.ddcs.model.SolarMan;

public interface SolarManMapper extends BaseMapper<SolarMan>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_solarman
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	@Override
	int insert(SolarMan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_solarman
	 * @mbggenerated  Tue Jul 31 15:48:01 CST 2018
	 */
	int insertSelective(SolarMan record);
	
	int batchInsert(List<SolarMan> list);
}